source 'https://rubygems.org'
ruby "2.4.0"

gem 'sinatra'
gem 'json'
gem 'dotenv'

gem 'sinatra-static-assets'
gem 'sinatra-contrib'

group :test, :development do
  gem 'shotgun'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'vcr'  
  gem 'webmock'
end
